targets:
  $default:
    sources:
      include:
        - pubspec.yaml
        - lib/**
        - templates/**
        - $package$
    builders:
      ngdart_cli:
        generate_for:
          - lib/src/templates/*.dart
        enabled: true

builders:
  ngdart_cli:
    import: "lib/src/util/builder.dart"
    builder_factories: ["buildTemplate"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source