name: ngdart_cli
description: A command-line tool for creating and managing AngularDart projects.
version: 1.3.0
homepage: https://github.com/angulardart-community/ngdart_cli
repository: https://github.com/angulardart-community/ngdart_cli

executables:
  ngdart: ngdart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1
  args: ^2.3.1
  build: ^2.3.0
  cli_util: ^0.3.5
  dart_style: ^2.2.3
  glob: ^2.0.2
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies: 
  build_config: ^1.0.0
  build_runner: ^2.1.11
  build_version: ^2.1.1
  lint: ^1.8.2
  test: ^1.21.1

platforms:
  linux:
  macos:
  windows:
